spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/h2/h2-2.1.214/project/infli;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
hello: '{cipher}79566a3d24d057abd564fbc50e2e7544b36c68e7383b7a300f30327cb9cd0430'
