# default 설정
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{cipher}7b23ece329f0177cbbfeec788c94f8f9c76af868e1143c2b09c09a150a8b6a5b296ebee9344df30f2d441b8524cf76b7"
    password: "{cipher}620e733b05e0a1bfc4cfd002f59f11297063612824255f8caa2fb6a0047b1e35"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379

jwt:
  properties:
    secret: "{cipher}01486141a9d08208e625672f9c5f911e242c3af26576820a516fabfd90ed6c3afda7bea702953059e73ffea23a7fee77"
    access-token-expiration-seconds: 1800 # 30 min
    refresh-token-expiration-seconds: 1209600 # 14 days
    token-prefix: Bearer
    access-token-header-name: Access-Token
    refresh-token-header-name: Refresh-Token
